---
title: "Testing"
output: pdf_document
date: '2022-11-17'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(400)
library(bootstrap)
library(ggplot2)
```

AUTO

```{r}
carDB <- c(62,62,63,63,64,64,65,65,66,66,67,67,67,68,68,68,69,69,70,70,70,71,71,71,72,72,72,72,73,73,73,74,74,74,74,75,75,75,75,76,76)
carspeed <- c(30:70)
carspeed <- 1.60934*carspeed
carinfo <- data.frame(carspeed) |> cbind(carDB)
ggplot() +
  geom_point(aes(carspeed, carDB), data = carinfo)

## ------------------------------------------------------------------------
# set up the bootstrap
B <- 1000

for(b in seq_len(B)) {
  ## Your Turn: Do the bootstrap!
  ## get bs dataset
  idx_star <- sample(1:41, 1000, replace = TRUE)
  x_star <- carinfo[idx_star,]
}
```

```{r}
n <- 1000

set.seed(400)

carfunction <- function(n){
  dB <- x_star$carDB
  Mj <- rnorm(n, (46*12/(.26)),1)
#   Mj <-  rnorm(n, (46*12/(.26*x_star$carspeed)),1)
 #    rnorm(n, mean(x_star$carDB), sd(x_star$carDB))
     
# db <- x_star$carDB
 # Mj <- rnorm(n,14697*2.29-x_star$carspeed, 1)
  ESDB <- (Mj)/(x_star$carspeed)
  return(ESDB)
}

ESDB_stor <- data.frame(carfunction(n))

# carfunction(n)
mean(carfunction(n))
summary(carfunction(n))

#carfunction <- function(n){
#  dB <- rnorm(n, mean(x_star$carDB), sd(x_star$carDB))
#  Mj <- runif(n, (12143*2.3/1.609), (14697*2.3/1.609))
#  ESDB <- (Mj)/(dB)
#  return(ESDB)
#}

ESDB_stor <- data.frame(carfunction(n))

mean(carfunction(n))
summary(carfunction(n))
```

```{r}
ggplot() +
  geom_point(aes(x = x_star$carspeed, y = ESDB_stor$carfunction.n.))
```


```{r}

# With dB as an rnorm - will remove later

carfunction <- function(n){
  dB <- rnorm(n, 69.78,17.5)
  Mj <- runif(n,8.5*45,8.5*65)
  ESDB <- (Mj)/(dB)
  return(ESDB)
}

ESDB_stor <- carfunction(n)

# carfunction(n)
mean(carfunction(n))
summary(carfunction(n))

ggplot() +
  geom_point(aes(x = x_star$carspeed, y = ESDB_stor)) + geom_smooth()

```

MEDIUM TRUCK

```{r}
## Method with DB from sample data
# medium truck data
mediumtruckDB <- c(73,74,74,75,75,76,76,77,77,77,78,78,78,79,79,79,80,80,80,81,81,81,82,82,82,82,83,83,83,83,84,84,84,84,85,85,85,85,86,86,86)

mediumtruckinfo <- data.frame(carspeed) |> cbind(mediumtruckDB)

ggplot() +
  geom_point(aes(carspeed, mediumtruckDB), data = mediumtruckinfo)

#------------------------------------------------------------------

for(b in seq_len(B)) {
  ## Your Turn: Do the bootstrap!
  ## get bs dataset
  mediumidx_star <- sample(1:41, 1000, replace = TRUE)
  mediumx_star <- mediumtruckinfo[mediumidx_star,]
}

n <- 1000

set.seed(400)

mediumtruckfunction <- function(n){
  dB <- mediumx_star$mediumtruckDB
  Mj <- runif(n,8.5*45,8.5*65)
  ESDB <- (Mj)/(dB)
  return(ESDB)
}

ESDB_stor <- data.frame(mediumtruckfunction(n))

# mediumtruckfunction(n)
mean(mediumtruckfunction(n))
summary(mediumtruckfunction(n))
```

```{r}
## Method with dB as an rnorm
```

HEAVY TRUCK 

```{r}
## Method with DB from sample data

# heavy truck data
heavytruckDB <- c(80,80,81,81,81,82,82,82,82,83,83,83,84,84,84,84,85,85,85,85,85,86,86,86,86,86,87,87,87,87,87,88,88,88,88,88,88,89,89,89,89)

heavytruckinfo <- data.frame(carspeed) |> cbind(heavytruckDB)

ggplot() +
  geom_point(aes(carspeed, heavytruckDB), data = heavytruckinfo)

#------------------------------------------------------------------

for(b in seq_len(B)) {
  ## Your Turn: Do the bootstrap!
  ## get bs dataset
  heavyidx_star <- sample(1:41, 1000, replace = TRUE)
  heavyx_star <- heavytruckinfo[heavyidx_star,]
}

n <- 1000

set.seed(400)

heavytruckfunction <- function(n){
  dB <- heavyx_star$heavytruckDB
  Mj <- runif(n,8.5*45,8.5*65)
  ESDB <- (Mj)/(dB)
  return(ESDB)
}

heavy_ESDB_stor <- data.frame(heavytruckfunction(n))

# heavytruckfunction(n)
mean(heavytruckfunction(n))
summary(heavytruckfunction(n))


```

```{r}

## Method with dB as an rnorm
heavy_rnormfunction <- function(n){
  dB <- heavyx_star$carspeed*1.609
 # Mj <- rnorm(n,(16.6*100*3.7854)/(43),1)   
    Mj <- rnorm(n, (43*300/(.26*1.609)),1)
#  Mj <- (rnorm(n,43*(heavyx_star$carspeed*1.609)-(heavyx_star$carspeed*1.609),1))
  
  # abs(rnorm(n,43*(heavyx_star$carspeed*1.609)-(heavyx_star$carspeed*1.609)^2,1))

    
    
    #runif(n,1.60934*heavyx_star$carspeed*13.4,1.60934*heavyx_star$carspeed*16.6)

    
  
  ESDB <- ((Mj)/heavyx_star$carspeed)
  return(ESDB)
}

#For Mj above, 35 and 43 came from the link I used to find 13.4 and 16.6

heavy_ESDB_stor <- heavy_rnormfunction(n)

heavy_rnormfunction(n)
mean(heavy_rnormfunction(n))
summary(heavy_rnormfunction(n))

ggplot() +
  geom_point(aes(x = heavyx_star$carspeed, y = heavy_ESDB_stor)) + geom_smooth()

```





